### ISSUE TITLE
Possible issues about the BigSur update on Mac OS

### ISSUE THREAD

**Issue by elfnrpyrz** [mmmlab/cogsp-lab-code#3]
I was rerunning all the experiments. I realized that the Line Length and the Attentional Blink experiments that used to run without a problem on Mac OS Catalina version 10.15.6, now doesn't respond to any key inputs on the machine running Mac OS BigSur version 11.1. 

The first screen with the instructions appear, then when I press a button to proceed with the experiment, nothing happens. ESC doesn't work as well. I had to force restart my PC multiple times. This issue doesn't happen on a Windows machine, both codes run smoothly.

**Comment by melchimm** [comment]
Has anyone else on MacOS experienced this problem?

I don't have a Mac available, so we'll have to wait for confirmation.

**Comment by elfnrpyrz** [comment]
Hi, this issue still persists with BigSur with the Line Length experiment. The issue is exactly the same. I had a considerable amount of students emailing about the exact thing happening and they had MacOS.

**Comment by melchimm** [comment]
Elif,

Sorry for the delay. I've asked Mimi to take a look at this because I don't have access to a machine with Big Sur installed.

**Comment by melchimm** [comment]
This was apparently fixed by the most recent code push (on 9/23/2021), so I'm closing this issue.
