### ISSUE TITLE
DividedAttention Instructions not presented

### ISSUE THREAD

**Issue by laurasaad14** [mmmlab/cogsp-lab-code#5]
Using Windows 10, PsychoPy 2021.2.3. DividedAttention.py file -- Instructions not presented on first screen. The instructions flash by before you can read them. First screen that holds says "Trial 1 press key". Would also be useful to change that instruction to "press any key" or something similar.

**Comment by melchimm** [comment]
Which file are you using (i.e., "DividedAttention-Tilt.py" or "DividedAttention-Color.py")? 
Note that there is no "DividedAttention.py" file in the repository.

**Comment by melchimm** [comment]
I've addressed these issues in both files.
