### ISSUE TITLE
Mental Rotation doesn't quit

### ISSUE THREAD

**Issue by elfnrpyrz** [mmmlab/cogsp-lab-code#7]
Once the Mental Rotation experiment is done, and the instructions to create a figure appears, pressing the space bar doesn't work.  This happens both on Windows 10 & Mac running Monterey. I've realized that it creates the figure (assumingly this happens once you press space), but doesn’t close the experiment page. That’s why you can’t do anything else/ or see the figure.  Quitting with escape works before the experiment finishes. But once the experiment is done, esc or force quit doesn’t work. I've tried to force quit both with Alt+F4 and also tried to open up Task Manager. Since Task manager also comes up in a window, you can't see it on the screen. I believe this error occurs because the experiment screen takes over the whole screen and even with Alt+Tab you cannot select and view other windows that are open.

**Comment by melchimm** [comment]
Elif,

It works fine on my machine, but I'm guessing that the problem has something to do with the data plotting routine at the end.
That routine doesn't work as intended anyway, so I've commented it out and updated the repo. Please try this version of the task and let me know whether or not the problem persists.

**Comment by elfnrpyrz** [comment]
Hello, 

I've run the latest version and the program quit just fine, everything was smooth. Thank you~
